secao/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("add/", views.add, name="add"),  
    path("<int:pk>/", views.detalhe_secao, name="detalhe_secao"),
    path("listar_secoes/", views.listar_secoes, name="listar_secoes"),  # ✅ Corrigido
    path("del/<int:pk>/", views.delete, name="delete"),
]

sumarizacao_GIST/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from algoritmo import sumarizacao

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("secao.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

secao/models.py
from django.db import models

class Secao(models.Model):
    TIPO_ENTRADA_CHOICES = [
        ('url', 'URL'),
        ('file', 'Arquivo'),
    ]

    nome = models.CharField(max_length=100)
    texto_resposta = models.TextField(blank=True)
    tipo_entrada = models.CharField(max_length=10, choices=TIPO_ENTRADA_CHOICES)
    url = models.URLField(blank=True, null=True) 
    arquivo = models.FileField(upload_to='uploads/', blank=True, null=True)  
    imagem_nuvem = models.CharField(max_length=255, blank=True, null=True)

secao/forms.py
from django import forms
from .models import Secao

class SecaoForm(forms.ModelForm):
    class Meta:
        model = Secao
        fields = ['tipo_entrada', 'url', 'arquivo']
        widgets = {
            'tipo_entrada': forms.Select(attrs={
                'class': 'form-select form-select-lg mb-3',
                'style': 'max-width: 500px;'
            }),
            'url': forms.URLInput(attrs={
                'class': 'form-control form-control-lg mb-3',
                'placeholder': 'Digite a URL...',
                'style': 'max-width: 500px;'
            }),
            'arquivo': forms.ClearableFileInput(attrs={
                'class': 'form-control form-control-lg mb-3',
                'style': 'max-width: 500px;'
            }),
        }

secao/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponseBadRequest
from django.template.loader import render_to_string
from django.http import  HttpResponseRedirect
from .models import Secao as Secao
from .forms import SecaoForm

# Create your views here.
def home(request):
    secoes = Secao.objects.all().order_by('-id')
    form = SecaoForm()
    context = {
        'secoes': secoes,
        'form': form,
    }
    return render(request, "secao/index.html", context)

def add(request):
    if request.method == 'POST':
        form = SecaoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')  
        else:
            return render(request, "secao/_add.html", {'form': form})  

    else:
        form = SecaoForm()
        html = render_to_string("secao/_add.html", {'form': form}, request=request)
        return JsonResponse({'success': True, 'html': html})


def listar_secoes(request):
    secoes = Secao.objects.all().order_by('-id')
    html = render_to_string("_nav.html", {'secoes': secoes}, request=request)
    return JsonResponse({'html': html})


def detalhe_secao(request, pk):
    if not request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return HttpResponseBadRequest("Requisição inválida")
    secao = get_object_or_404(Secao, pk=pk)
    html = render_to_string("secao/_detail.html", {'secao': secao}, request=request)
    return JsonResponse({'html': html})


def delete(request, pk):
    Secao.objects.get(pk=pk).delete()
    return redirect('home')

templates/_base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Sumarização Gist</title>
        <!-- Favicon-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
            <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body style="margin: 0; overflow: hidden;">
        <div class="d-flex h-100" id="wrapper">
            {% include '_nav.html' %}
            <div id="page-content-wrapper" class="w-100">
                {% include '_header.html' %}
                <div id="main-content" class="d-flex align-items-center justify-content-center h-100 w-100" style="max-height: 90%; overflow-y: auto;">
                    
                         {% block content %}
                         {% endblock %}
                     
                </div>
    
            </div>
        </div>
    </body>
    
    <script src="{% static 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js'%}"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js'%}"></script>
     <script src="{% static 'js/functions.js' %}"></script>
</html>

templates/_header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <button class="btn" id="sidebarToggle" aria-label="Abrir menu lateral">
            <i class="bi bi-layout-sidebar" style="font-size: 1.5rem;"></i>
        </button>

    </div>
</nav>

templates/_nav.html
<div class="border-end bg-white" id="sidebar-wrapper">
  <div class="sidebar-heading d-flex justify-content-between align-items-center px-3 py-8 mt-2">
    Sumarização Gist
    <a href="#" onclick="carregarFormulario()" title="Adicionar URL e arquivo">
      <i class="bi bi-pencil-square" style="font-size: 1.2rem; color: #000;"></i>
    </a>
  </div>

  <div class="list-group list-group-flush m-1">
    {% for secao in secoes %}
    <div class="d-flex align-items-center justify-content-between list-group-item py-3 px-4 rounded border-0 position-relative"
         style="background-color: #f8f9fa; transition: background-color 0.2s; margin-bottom: 0.5rem;">
      
      <a href="#" class="text-decoration-none text-dark flex-grow-1 link-secao word-wrap: break-word;" data-pk="{{ secao.id }}">
        {{ secao.nome }}
      </a>

      <button class="btn btn-light ms-0 toggle-menu" style="padding: 0.25rem;">
        <i class="bi bi-three-dots" style="font-size: 0.9rem;"></i>
      </button>

      <div class="menu-opcoes position-absolute end-0 mt-5 p-2 bg-white shadow rounded d-none" style="z-index: 1000;">
        <a href="del/{{ secao.id }}/" class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<script>
document.addEventListener("click", function (e) {
  const isMenuButton = e.target.closest(".toggle-menu");
  const isInsideMenu = e.target.closest(".menu-opcoes");

  if (isMenuButton) {
    document.querySelectorAll(".menu-opcoes").forEach(menu => {
      menu.classList.add("d-none");
    });

    const container = isMenuButton.closest(".list-group-item");
    const menu = container.querySelector(".menu-opcoes");
    menu.classList.toggle("d-none");

    e.stopPropagation(); 
    return;
  }

  if (!isInsideMenu) {
    document.querySelectorAll(".menu-opcoes").forEach(menu => {
      menu.classList.add("d-none");
    });
  }
});
</script>

templates/secao/_add.html
<form  id="form-secao" action="add/" method="POST" enctype="multipart/form-data" class="w-100">
  {% csrf_token %}
  <div class="mb-3 text-center">
      <label for="id_tipo_entrada" class="form-label">Tipo de Entrada</label>
      <div class="d-flex justify-content-center">
        {{ form.tipo_entrada }}
      </div>
    </div>
  
    <div class="mb-3 text-center" id="campo-url">
      <label for="id_url" class="form-label">URL</label>
      <div class="d-flex justify-content-center">
        {{ form.url }}
      </div>
    </div>
  
    <div class="mb-3 text-center" id="campo-arquivo">
      <label for="id_arquivo" class="form-label">Arquivo</label>
      <div class="d-flex justify-content-center">
        {{ form.arquivo }}
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
  
</form>

templates/secao/_detail.html
<div style="max-width: 50vw; max-height: 80vh;">
  <div class="card mt-5 mx-auto p-3"> 
    <div class="text-center my-4"> 
  <img src="/media/clouds/{{ secao.imagem_nuvem }}" class="img-fluid rounded" alt="Nuvem de Palavras" style="max-width: 100%; height: auto;">
</div>
    <p class="card-text" style="
      white-space: normal;
      text-align: justify;
      text-justify: inter-word;
      hyphens: auto;
      font-size: 1.1rem;
      line-height: 1.75;
      padding: 1rem;
    ">
      {{ secao.texto_resposta }}
    </p>
  </div>
</div>

templates/secao/index.html
{% extends '_base.html' %}

{% block content %}

{% include "secao/_add.html" %}

{% endblock %}